#! /bin/sh
xmodmap ~/.Xmodmap
sxhkd &
#if [ "connected" == "$(</sys/class/drm/card0/card0-DP-1/status )" ]
#        bspc monitor DP1 -n 0 -d I II III IV V
#        bspc monitor eDP1 -n 1 -d VI VII VIII IX X
#else
#        bspc monitor -d I II III IV V VI VII VIII IX X
#fi
i=0
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( 10 / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sh /home/orvyx/scripts/monitor_hotplug.sh




urxvtd -q -f -o
sh ~/scripts/theme_random.sh
wal-steam -w
#xrdb -merge ~/.Xresources
sh ~/scripts/polybar_launch.sh
nm-applet sm-disable &
#pasystray

compton -cCzG -t-3 -l-5 -r4 --config /dev/null --backend xrender --unredir-if-possible
pasystray
